name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Production

    env: 
      API_IMAGE_NAME: putto2002/api
      DASHBOARD_IMAGE_NAME: putto2002/dashboard

    steps:
    - uses: actions/checkout@v3
  
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build API Docker Image
      run: docker build . --target api --tag ${{env.API_IMAGE_NAME}}:lastest --tag ${{env.API_IMAGE_NAME}}:${{github.sha}}
    - name: Push API Docker Image
      run: docker push ${{env.API_IMAGE_NAME}}:lastest
    - name: Build Dashboard Docker Image
      run: docker build . --target dashboard --tag ${{env.DASHBOARD_IMAGE_NAME}}:lastest --tag ${{env.DASHBOARD_IMAGE_NAME}}:${{github.sha}}
    - name: Push Dashboard Docker Image
      run: docker push ${{env.DASHBOARD_IMAGE_NAME}}:lastest

  deploy_db: 
    runs-on: ubuntu-lastest
    environment: Production

    strategy:
      matrix:
        node-version: [18]

    steps: 
    - uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install Prisma CLI
      run: pnpm install prisma
    - name: Deploy Migrations
      run: pnpm prisma migrate deploy
      env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
    
  

      
      
  
