name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: 
      - closed
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Production

    env: 
      API_IMAGE_NAME: putto2002/api
      DASHBOARD_IMAGE_NAME: putto2002/dashboard
      PUBLIC_WEB_IMAGE_NAME: putto2002/publicweb

    steps:
    - uses: actions/checkout@v3
  
    - name: Build API Docker Image
      run: docker build . --target api --tag ${{env.API_IMAGE_NAME}}:lastest --tag ${{env.API_IMAGE_NAME}}:${{github.sha}}
    - name: Build Dashboard Docker Image
      run: docker build . --build-arg API_BASE_URL=${{vars.API_BASE_URL}} --target dashboard --tag ${{env.DASHBOARD_IMAGE_NAME}}:lastest --tag ${{env.DASHBOARD_IMAGE_NAME}}:${{github.sha}}
    - name: Build Public Web Docker Image
      run: docker build . --target public-web --tag ${{env.PUBLIC_WEB_IMAGE_NAME}}:lastest --tag ${{env.PUBLIC_WEB_IMAGE_NAME}}
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push API Docker Image
      run: docker push ${{env.API_IMAGE_NAME}}:lastest
    - name: Push Dashboard Docker Image
      run: docker push ${{env.DASHBOARD_IMAGE_NAME}}:lastest
    - name: Push Public Web Docker Image
      run: docker push ${{env.PUBLIC_WEB_IMAGE_NAME}}:lastest

  # Only deploy the database when the main branch is pushed
  deploy_db: 
    needs: build
    runs-on: ubuntu-latest
    environment: Production

    strategy:
      matrix:
        node-version: [18]

    steps: 
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install Prisma CLI
      run:  | 
            pnpm install prisma -g
            ls
    - name: Deploy Migrations
      run: pnpm prisma migrate deploy
      env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  invoke_deployment:
    runs-on: ubuntu-latest
    needs: [build, deploy_db]
    environment: Production
    steps: 

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
            webhook_url: ${{ secrets.WEBHOOK_URL }}

