name: Build

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Production

    env: 
      API_IMAGE_NAME: putto2002/api
      DASHBOARD_IMAGE_NAME: putto2002/dashboard

    steps:
    - uses: actions/checkout@v3
  
    - name: Build API Docker Image
      run: docker build . --target api --tag ${{env.API_IMAGE_NAME}}:lastest --tag ${{env.API_IMAGE_NAME}}:${{github.sha}}
    - name: Build Dashboard Docker Image
      run: docker build . --build-arg API_BASE_URL=${{vars.API_BASE_URL}} --target dashboard --tag ${{env.DASHBOARD_IMAGE_NAME}}:lastest --tag ${{env.DASHBOARD_IMAGE_NAME}}:${{github.sha}}
  
