name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_docker_images:

    runs-on: ubuntu-latest

    env: 
      API_IMAGE_NAME: putto2002/api
      DASHBOARD_IMAGE_NAME: putto2002/dashboard

    steps:
    - uses: actions/checkout@v3
  
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build API Docker Image
      run: docker build . --taget api --tag ${{env.API_IMAGE_NAME}}:lastest --tag ${{env.API_IMAGE_NAME}}:${{github.sha}}
    - name: Push API Docker Image
      run: docker push ${{env.API_IMAGE_NAME}}:lastest
    - name: Build Dashboard Docker Image
      run: docker build . --taget dashboard --tag ${{env.DASHBOARD_IMAGE_NAME}}:lastest --tag ${{env.DASHBOARD_IMAGE_NAME}}:${{github.sha}}
    - name: Push Dashboard Docker Image
      run: docker push ${{env.DASHBOARD_IMAGE_NAME}}:lastest

      
      
  
